### ISSUE TITLE
Couldn't load plugin 'CloudMasking' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by Almeida100** [SMByC/CloudMasking#3]
Hi,
I have QGis 3.12.3 installed from the 32-bit OSGeo4W and this error message appears. I am working with SCP 6.4.7.
How can I overcome this problem?

Couldn't load plugin 'CloudMasking' due to an error when calling its classFactory() method 

ImportError: DLL load failed: Impossível localizar o módulo especificado.  [Unable to find the specified module.]
Traceback (most recent call last):
  File "C:/Users/Toni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\__init__.py", line 32, in fmask_libs
    from CloudMasking.libs.fmask import _fillminima, _valueindexes
ImportError: cannot import name '_fillminima' from 'CloudMasking.libs.fmask' (C:/Users/Toni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\libs\fmask\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/OSGeo4W/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Toni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\__init__.py", line 100, in classFactory
    fmask_libs()
  File "C:/Users/Toni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\CloudMasking\__init__.py", line 65, in fmask_libs
    from CloudMasking.libs.fmask.win32_py36 import _fillminima, _valueindexes
  File "C:/OSGeo4W/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed: Impossível localizar o módulo especificado.

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] 
QGIS version: 3.12.3-București București, 8234261527 

Python Path:
C:/OSGeo4W/apps/qgis/./python
C:/Users/Toni/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Toni/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\Python37
C:\OSGeo4W\apps\Python37\Scripts
C:\OSGeo4W\bin\python37.zip
C:\OSGeo4W\apps\Python37\DLLs
C:\OSGeo4W\apps\Python37\lib
C:\OSGeo4W\bin
C:\Users\Toni\AppData\Roaming\Python\Python37\site-packages
C:\Users\Toni\AppData\Roaming\Python\Python37\site-packages\win32
C:\Users\Toni\AppData\Roaming\Python\Python37\site-packages\win32\lib
C:\Users\Toni\AppData\Roaming\Python\Python37\site-packages\Pythonwin
C:\OSGeo4W\apps\Python37\lib\site-packages
C:\OSGeo4W\apps\Python37\lib\site-packages\win32
C:\OSGeo4W\apps\Python37\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Toni/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by XavierCLL** [comment]
Hi,
CloudMasking plugin has the libs (DLLs) for a different version of Python but not for 32bits (no longer supported, sorry), use Python and Qgis (here OSGeo4W) of 64bits
